version: 2

jobs:
  
  test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout

      # get the build-essentials so we can compile
      - run: sudo apt-get update && sudo apt-get install build-essential

      # create venv and install dependencies
      - run:
          name: Install Python deps
          command: sudo pip install -r requirements.txt

      # install git-annex
      - run: curl https://downloads.kitenet.net/git-annex/linux/current/git-annex-standalone-amd64.tar.gz | tar -xvz  && sudo mv git-annex.linux/* /usr/local/bin

      # run unit tests
      - run: pytest

  deploy-prod:
    steps:
      - checkout
      
      # login
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      
      # build datalad-service 
      - run: docker build --pull -t openneuro/datalad-service

      # update latest tag
      - run: docker tag -f openneuro/datalad-service openneuro/datalad-service:latest
      - run: docker push openneuro/datalad-service
  deploy-dev:
    steps:
      - checkout
      
      # login
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      
      # build datalad-service 
      - run: docker build --pull -t openneuro/datalad-service

      # update latest tag
      - run: docker tag -f openneuro/datalad-service openneuro/datalad-service:$CIRCLE_TAG
      - run: docker push openneuro/datalad-service:$CIRCLE_TAG

workflows:
  version: 2
  build:
    jobs:
      - test
      - deploy-prod:
        # filters:
        #   branches:
        #     only: 
        #     - master
        requires:
          - test
